version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "2222:2222"
    networks:
      - common-network

  ordersservice:
    image: ordersservice
    ports:
      - "4444:4444"
    networks:
      - common-network

  catalogservice:
    image: catalogservice
    ports:
      - "3333:3333"
    networks:
      - common-network

  catalogserviceii:
    image: catalogserviceii
    ports:
      - "3334:3334"
    networks:
      - common-network

  ordersserviceii:
    image: ordersserviceii
    ports:
      - "4445:4445"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
